### ISSUE TITLE
Add date to tracker

### ISSUE THREAD

**Issue by mybestrong** [yekenuk/meal-tracker#47]
Please could King Ali add the date to the tracker screen? 

It will help when editing a past or future tracker if you can see the date of the tracker your editing.

Not sure if I described it too well. King Ali will decipher it 🤴

**Comment by yekenuk** [comment]
lol - I get it.

Working on it.

**Comment by yekenuk** [comment]
Done. Will be in next 0.4 beta.

**Comment by mybestrong** [comment]
You don’t mess about! Long live the king!! 🤴
